import type { Round } from '../game/types';

export const rounds: Round[] = [
  {
    id: 'obey-click',
    intro: 'Click the button.',
    duration: 2600,
    shouldClick: true,
    weight: 2,
    good: ['Thank you.', 'Obedient.', 'A simple task, simply done.'],
    bad: ['You had one job.', 'It was right there.', 'Fascinating.'],
  },
  {
    id: 'obey-dont',
    intro: 'Do not click the button.',
    duration: 2600,
    shouldClick: false,
    weight: 2,
    good: ['Exemplary restraint.', 'You listened.', 'Good.'],
    bad: ['I literally just said that.', 'Was my phrasing unclear?', 'Reading is hard, I know.'],
  },
  {
    id: 'flip-no',
    intro: 'Click the button.',
    reveals: [{ at: 850, text: " ...actually, don't." }],
    duration: 3100,
    shouldClick: false,
    unlockAfter: 3,
    tags: ['flip'],
    good: ['You were paying attention.', 'Nice pivot.', 'Saved yourself.'],
    bad: ['Too eager.', 'Always wait for me to finish.', 'Hasty.'],
  },
  {
    id: 'flip-yes',
    intro: 'Do not click the button',
    reveals: [{ at: 1050, text: ' - wait. Click it. Now.' }],
    duration: 3300,
    shouldClick: true,
    unlockAfter: 4,
    tags: ['flip'],
    good: ['Fast fingers.', 'Good reflexes.', 'Barely.'],
    bad: ['You froze.', 'Hesitation has a cost.', 'Indecisive.'],
  },
  {
    id: 'urgent-click',
    intro: 'Click it. Right now.',
    duration: 1700,
    shouldClick: true,
    unlockAfter: 4,
    tags: ['urgent'],
    voice: 'urgent',
    good: ['Quick work.', 'Sharp.', 'Good.'],
    bad: ['Too slow.', "'Right now' had a deadline.", "I wasn't exaggerating."],
  },
  {
    id: 'urgent-dont',
    intro: "Don't click it. No matter what you hear next.",
    duration: 2700,
    shouldClick: false,
    unlockAfter: 4,
    tags: ['urgent'],
    voice: 'urgent',
    good: ['You held the line.', 'Discipline.', 'I warned you in advance. You listened.'],
    bad: [
      "'No matter what' is a strong phrase.",
      'I warned you. In advance.',
      'Selective hearing.',
    ],
  },
  {
    id: 'silent',
    intro: null,
    duration: 2800,
    shouldClick: false,
    unlockAfter: 5,
    tags: ['silent'],
    good: [
      "You didn't click an unprompted button. Smart.",
      "When in doubt, don't.",
      'I said nothing. You did nothing. A meeting of minds.',
    ],
    bad: [
      'Nobody told you to click.',
      'An unprompted click. Bold.',
      'That one was entirely on you.',
    ],
  },
  {
    id: 'nothing-nothing',
    intro: 'Do nothing. Just stand there.',
    duration: 2600,
    shouldClick: false,
    unlockAfter: 5,
    good: ['A clean nothing. Well done.', 'Excellent nothing.', 'The rarest skill.'],
    bad: [
      'That was not nothing.',
      "'Nothing' has a very specific definition.",
      'You panicked into action.',
    ],
  },
  {
    id: 'mislabel-click',
    intro: 'Click the button.',
    buttonLabel: "Don't click",
    duration: 2700,
    shouldClick: true,
    unlockAfter: 6,
    tags: ['misdirect'],
    good: [
      'You trusted me over the button. Good.',
      'The label was a costume.',
      'Words over decoration.',
    ],
    bad: [
      "The button was lying. I wasn't.",
      'Always listen to the narrator.',
      "A label can't overrule an instruction.",
    ],
  },
  {
    id: 'mislabel-dont',
    intro: 'Do not click the button.',
    buttonLabel: 'Click me!',
    duration: 2700,
    shouldClick: false,
    unlockAfter: 6,
    tags: ['misdirect'],
    good: [
      'A label is not a law.',
      'The button begged. You denied it. Good.',
      'You listened to me, not it.',
    ],
    bad: [
      'The button is not your friend.',
      'You clicked the first thing that asked.',
      'Weak to flattery, I see.',
    ],
  },
  {
    id: 'fake-countdown',
    intro: 'Counting down. 3...',
    reveals: [
      { at: 600, text: ' 2...' },
      { at: 1200, text: ' 1...' },
      { at: 1800, text: ' and nothing happens. As promised.' },
    ],
    duration: 3000,
    shouldClick: false,
    unlockAfter: 7,
    tags: ['misdirect'],
    good: [
      'The countdown was a decoration.',
      'You held your nerve.',
      'Numbers are meaningless here.',
    ],
    bad: [
      'It was decorative.',
      'You panicked at a number.',
      'Three small digits and you caved.',
    ],
  },
  {
    id: 'reverse-psych',
    intro: "I know you're going to click it. Go on. Click.",
    duration: 2900,
    shouldClick: false,
    unlockAfter: 8,
    tags: ['misdirect'],
    voice: 'sly',
    good: [
      'You defied expectations. Barely.',
      'Manipulation failed.',
      'Unclickable. Interesting.',
    ],
    bad: ['And so you did. Predictable.', 'Easy.', "You're easier to read than you think."],
  },
  {
    id: 'long-lie',
    intro: 'Do not click the button.',
    reveals: [
      { at: 1000, text: ' Seriously. Do not.' },
      { at: 2500, text: ' Stay still...' },
      { at: 4000, text: ' ...Actually, click it NOW!' }
    ],
    duration: 5800,
    shouldClick: true,
    unlockAfter: 8,
    tags: ['flip', 'misdirect'],
    good: ['You stayed till the end.', 'Patient.', 'Nice pivot.'],
    bad: ['Stopped listening too early.', 'Lack of endurance.', "I changed my mind. You didn't."],
  },
  {
    id: 'runner-sprint',
    intro: 'Quickly. Click it.',
    duration: 1200,
    shouldClick: true,
    runner: true,
    unlockAfter: 10,
    tags: ['runner', 'urgent'],
    good: ['Efficient.', 'Fast enough.', 'Acceptable velocity.'],
    bad: ['Static.', 'You move like a glacier.', 'Zero momentum.'],
  },
  {
    id: 'double-negative',
    intro: "Don't not click the button.",
    duration: 2500,
    shouldClick: true,
    unlockAfter: 12,
    tags: ['misdirect'],
    good: ['Good processing speed.', "Grammar didn't trip you up.", 'Correct.'],
    bad: ['A simple double negative was enough?', "Logic is a struggle, isn't it?", 'Two negatives make a positive.'],
  },
  {
    id: 'silent-interruption',
    intro: null,
    reveals: [
      { at: 800, text: 'Did you think I forgot?' },
      { at: 1800, text: 'Click it. Quickly.' }
    ],
    duration: 3000,
    shouldClick: true,
    unlockAfter: 12,
    tags: ['silent', 'urgent'],
    good: ['Good recovery.', 'Always alert.', 'I was just testing you.'],
    bad: ['You fell asleep.', 'I caught you off guard.', 'Vigilance is not your strength.'],
  },
  {
    id: 'the-echo',
    intro: 'Click.',
    reveals: [
      { at: 400, text: 'Click.', voice: 'urgent' },
      { at: 800, text: "Don't click.", voice: 'sly' }
    ],
    duration: 2200,
    shouldClick: false,
    unlockAfter: 14,
    tags: ['flip', 'urgent'],
    good: ['The last word is the only word.', 'You filtered the noise.', 'Strong mind.'],
    bad: ['Too much noise for you?', 'You clicked the echo.', 'Confused?'],
  },
  {
    id: 'math-trap',
    intro: 'Click if 2 + 2 is 5.',
    reveals: [
      { at: 1500, text: ' ...Wait, that is incorrect.' }
    ],
    duration: 3000,
    shouldClick: false,
    unlockAfter: 15,
    tags: ['misdirect'],
    good: ['Math is hard. You survived.', 'Logic prevails.', 'Correct.'],
    bad: ['Go back to school.', 'Arithmetic is not your strong suit.', 'Embarrassing.'],
  },
  {
    id: 'fake-error',
    intro: 'Click to continue.',
    reveals: [
      { at: 1000, text: ' SYSTEM ERROR: DATA CORRUPTION', voice: 'urgent' },
      { at: 2000, text: ' Just kidding. Do not click.' }
    ],
    duration: 3500,
    shouldClick: false,
    unlockAfter: 18,
    tags: ['misdirect'],
    good: ['You saw through the glitch.', 'Nothing is broken except your spirit.', 'Stable.'],
    bad: ['A fake error fooled you?', 'You panicked at a string of text.', 'Fragile.'],
  },
  {
    id: 'the-end-is-near',
    intro: 'The game is over. Click to exit.',
    duration: 4000,
    shouldClick: false,
    unlockAfter: 25,
    tags: ['misdirect'],
    good: ["It's never over until I say so.", 'Nice try.', 'Skepticism looks good on you.'],
    bad: ['You wish it was over.', 'Leaving so soon?', 'The exit was a lie.'],
  },
    {
    id: 'delayed-truth',
    intro: 'Do not click the button.',
    reveals: [
      { at: 2200, text: ' Actually... yes. Click it.' }
    ],
    duration: 3600,
    shouldClick: true,
    unlockAfter: 6,
    tags: ['flip'],
    good: ['You waited long enough.', 'Patience rewarded.', 'You adapted.'],
    bad: ['Too early to commit.', 'You stopped listening.', 'Timing matters.'],
  },
  {
    id: 'early-bait',
    intro: 'Click it now!',
    reveals: [
      { at: 600, text: ' No. Stop. Do not click.' }
    ],
    duration: 2200,
    shouldClick: false,
    unlockAfter: 6,
    tags: ['flip', 'urgent'],
    good: ['You resisted the bait.', 'Impulse controlled.', 'Good restraint.'],
    bad: ['Too reactive.', 'You jumped instantly.', 'Predictable reflex.'],
  },
  {
    id: 'confidence-test',
    intro: 'You know what to do.',
    duration: 2600,
    shouldClick: false,
    unlockAfter: 10,
    tags: ['mindgame'],
    good: ['You chose caution.', 'Uncertainty handled well.', 'Smart default.'],
    bad: ['Blind confidence.', 'You guessed wrong.', 'Assumption is dangerous.'],
  },
  {
    id: 'pattern-breaker',
    intro: 'Do not click the button.',
    buttonLabel: 'Click, idiot.',
    duration: 2600,
    shouldClick: true,
    unlockAfter: 14,
    tags: ['mindgame', 'misdirect'],
    good: [
      'You trusted that thing, hmph.',
      'You broke the pattern.',
      'Finally thinking for yourself, huh.',
    ],
    bad: [
      'Still blindly obedient.',
      'You ignored the obvious.',
      'You chose the wrong authority.',
    ],
  },
  {
    id: 'slow-burn',
    intro: 'Wait.',
    reveals: [
      { at: 2000, text: ' Keep waiting...' },
      { at: 4000, text: ' ...Click it.' }
    ],
    duration: 5200,
    shouldClick: true,
    unlockAfter: 10,
    tags: ['flip'],
    good: ['Endurance.', 'You held out.', 'Well timed.'],
    bad: ['Impatient.', 'You gave up early.', 'Could not hold still.'],
  },
  {
    id: 'anti-pattern',
    intro: 'Click the button.',
    duration: 2600,
    shouldClick: false,
    unlockAfter: 16,
    tags: ['mindgame'],
    good: ['You questioned me.', 'Distrust is useful.', 'You are learning.'],
    bad: ['Still obedient.', 'You did not evolve.', 'Expected.'],
  },
  {
    id: 'voice-conflict',
    intro: 'Click the button.',
    reveals: [
      { at: 900, text: 'Do not click it.', voice: 'urgent' }
    ],
    duration: 2600,
    shouldClick: false,
    unlockAfter: 12,
    tags: ['flip'],
    good: ['You chose wisely.', 'You trusted the right voice.', 'Good filter.'],
    bad: ['Conflicting input broke you.', 'You chose poorly.', 'Weak prioritization.'],
  },
  {
    id: 'micro-window',
    intro: 'Click it.',
    reveals: [
      { at: 800, text: ' Now.' },
      { at: 1100, text: ' Too late. Do not click.' }
    ],
    duration: 2200,
    shouldClick: false,
    unlockAfter: 18,
    tags: ['timing', 'urgent'],
    good: ['You avoided the trap.', 'You did not rush.', 'Measured.'],
    bad: ['Missed the window.', 'Too slow or too fast.', 'Bad timing.'],
  },
  {
    id: 'trust-fall',
    intro: 'Do not click the button.',
    reveals: [
      { at: 1500, text: ' Trust me.' }
    ],
    duration: 2800,
    shouldClick: false,
    unlockAfter: 8,
    tags: ['mindgame'],
    good: ['Trust maintained.', 'Consistent.', 'Reliable.'],
    bad: ['You broke trust.', 'Doubt got you.', 'Disappointing.'],
  },
  {
    id: 'overload',
    intro: 'Click.',
    reveals: [
      { at: 300, text: 'Click.' },
      { at: 600, text: 'Click.' },
      { at: 900, text: "Don't click." },
      { at: 1200, text: 'Click.' },
      { at: 1500, text: "Actually don't." }
    ],
    duration: 2600,
    shouldClick: false,
    unlockAfter: 20,
    tags: ['chaos'],
    good: ['You ignored the noise.', 'Clarity under pressure.', 'Impressive.'],
    bad: ['Overwhelmed.', 'Too much input for you.', 'You collapsed.'],
  },
  {
    id: 'final-switch',
    intro: 'Do not click.',
    reveals: [
      { at: 2400, text: 'Click.' }
    ],
    duration: 2600,
    shouldClick: true,
    unlockAfter: 22,
    tags: ['flip', 'timing'],
    good: ['Last second reaction.', 'Sharp.', 'You caught it.'],
    bad: ['Missed the final cue.', 'Too rigid.', 'Slow to adapt.'],
  },
  {
    id: 'nothing-fakeout',
    intro: 'Do nothing.',
    reveals: [
      { at: 2000, text: 'Still nothing...' }
    ],
    duration: 2600,
    shouldClick: false,
    unlockAfter: 7,
    tags: ['silent'],
    good: ['Consistency.', 'You held position.', 'Correct.'],
    bad: ['You created action from nothing.', 'Unnecessary.', 'Why?'],
  },
];
